version: "3.9"

services:
  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=api.settings
    depends_on:
      - db

  app:
    build:
      context: ./app
    ports:
      - "5173:5173"
    volumes:
      - ./app:/app
    environment:
      - NODE_ENV=development

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: mydatabase

